version: '3'

services:
    web:
        build: .
        container_name: web
        restart: always
        networks:
            - nw
        env_file:
            - .env
        ports:
            - "443:80"
        environment:
            - PORT=80
            - NODE_ENV=production
        volumes:
            - ./config:/app/config
            - ./.ssl:/app/.ssl
            - ctf_files:/app/server/data/files
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - mongo_data:/data/db
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        env_file:
            - .env
        networks:
            - nw

volumes:
    mongo_data:
    ctf_files:

networks:
    nw:
        driver: bridge
